### ISSUE TITLE
Missing geometry in some light bins

### ISSUE THREAD

**Issue by NoSQLKnowHow** [jeroen94704/gridfinitycreator#21]
Hey. Found a problem in the light bins. I created a 2x2x5 and all is well. I create a 2x3x5 with or without labels and there is missing parts of the bin.
![image](https://github.com/jeroen94704/gridfinitycreator/assets/2966377/a30b3902-429d-4ea5-8c2b-f4cbb702b8ca)

**Comment by jeroen94704** [comment]
Thanks for the bug report once gain :). Should be fixed now.
