### ISSUE TITLE
Official Website Down? :/

### ISSUE THREAD

**Issue by wug-ge** [jeroen94704/gridfinitycreator#25]
Hi,

thank you for creating this amazing project, I've already generated a lot of stuff for my electronic parts storage and it's already sooo much better now!

The website seems to be quiet unstable though, I've noticed downtime's and it seems to be down now at least for the whole day.

I cloned it already but the setup didn't work out of the box for me, so before I dig deeper I thought I'll write an issue in case you were not aware of this problem til now.

Thanks for looking into it!

**Comment by jeroen94704** [comment]
Hi, thanks for reporting this. Yes, I am having some issues with my home server (power supply of my router died). It should be back up soon.

**Comment by jeroen94704** [comment]
OK, it's back up now, although there's a small chance the DNS change hasn't propagated everywhere yet (this can theoretically take up to 24 hours)

**Comment by wug-ge** [comment]
Hi @jeroen94704, thanks for replying so fast!

Unfortunately I can still not access the website nor ping it.

I'm getting this IP back:
PING bouwens.co (143.178.5.6) 

Could you have a look at it again?

**Comment by jeroen94704** [comment]
Hm, this is weird. When I first saw your message I also couldn't access it, but now I can. And I see in the logs it seems to be restarting every now and again, out of the blue. The IP you get is correct, and that you cannot ping it is also correct, since I blocked that :).

All I can say for now is "try again later", and I'll look into it.

**Comment by jeroen94704** [comment]
OK, it may have something to do with someone requesting a holey bin with 2340 holes in it :). That completely thrashed the server. I need to implement some sanity checking here, for example to ensure the keepout diameter is always larger than the hole diameter.

**Comment by jeroen94704** [comment]
@all-contributors please add @wug-ge for bug
