### ISSUE TITLE
Holey bin not generating bigger than 1x1

### ISSUE THREAD

**Issue by chasebolt** [jeroen94704/gridfinitycreator#28]
Setting Width/Length in grid-units to 2 does not generate a 2x2 grid. The downloaded file is always a 1x1.

**Comment by jeroen94704** [comment]
Ah, good catch. I see I missed a bit of javascript in the latest release. Will fix ASAP.

**Comment by jeroen94704** [comment]
I just released (and deployed) version 0.4.4, which has a fix for this issue. Thanks for reporting!

**Comment by jeroen94704** [comment]
https://github.com/all-contributors please add @chasebolt or bug

**Comment by jeroen94704** [comment]
[@all-contributors ](https://github.com/all-contributors) please add @chasebolt for bug
