### ISSUE TITLE
[Feature Request] Have measurements in metric for the units

### ISSUE THREAD

**Issue by NoSQLKnowHow** [jeroen94704/gridfinitycreator#3]
For the width, length, and height, they are on the page in units. It'd be nice to have their mm/cm equivalents there as well, especially for the height. I know how deep my drawer is in cm/mm, but then I have to look up the Gridfinity specs to know how many units that is. If it was on screen, that'd be far easier.

Also, that as the units change in the form field, the measurement dynamically changes too.

**Comment by jeroen94704** [comment]
This is part of the text describing the parameters for the bins
